### PR TITLE
add more transformers

### PR DESCRIPTION
**Pull request by tobybellwood**
This PR adds a few extra transformers for common AFL details.

### CODE REVIEW

**Review by timclifford — APPROVED** [review]

**Comment by timclifford** [comment]
@tobybellwood Happy for this to go in?

**Comment by tobybellwood** [comment]
@bomoko - want me to rewrite this in YAML?

**Comment by bomoko** [comment]
@tobybellwood please do :)

**Comment by tobybellwood** [comment]
@bomoko - updated this, and sorted by category - and added an additional category for "Service" that should be able to pick up what version of underlying service images is in use. I've not called these key_facts (yet) though - as I'm not sure on their status?

**Pull request merged**
